# Toddler friendly christmas tree stand

!(unpacked)[0unpacked.jpg]

This is a description of safe Christmas tree stand. Large base prevents the tree from collapsing. Only generally
available steel components were used (30mm and 25mm square steel tubes, water pipe). Some parts were welded together and some
are mounted with screws. This allows the construction to be very compact after disassembly. Outer diameter just 
9.5cm and length 44cm. 

!(packed)[1packed.jpg]

Legs are made from 25mm square steel tube of length 400mm. At the end there is a washer welded to the tube.
There are three long screws hidden in the legs which hold them together. Fourth leg has a 3D printed block on its 
end which holds 3x M8 flanged nuts where the screws go.

!(legs and screws)[2legs.jpg]

These very long screws are made by welding a 305mm M8 threaded rod with a M8 70mm cap head screw. Three M8 nyloc 
nuts and two 3D printed blocks are carefully placed to allow the screw move freely for fastening, but prevent it from 
falling out of the tube. 

!(rod)[7rod.jpg]

!(rod detail begin)[8rod.jpg]

!(rod detail end)[9rod.jpg]

!(legs and screw heads)[3legs.jpg]

The screw itself is a bit shorter (385mm) than the tube itself and when packed it is completely hidden. 

!(leg cross)[4cross.jpg]

After fastening these screws with a TORX screwdriver or a hex key, you should get a large cross like this.
There are 4 printed blocks which are used to lift whole construction and prevent the floor from scratching.
Eight M8/40mm screws and 3d printed parts are used to fasten the tree in the main pipe with just bare hands.

!(pipe cross)[5cross.jpg]

Inside the steel pipe (outer diameter 89mm, wall 4mm, length 180mm) there is are 30mm square steel tubes welded
to form a cross where the legs go.

!(nut)[6nut.jpg]

Eight M8 threaded holes were cut into the main stell pipe to keep the tree in place


## Bill of material
- Round steel pipe 80mm inner diameter, 4mm wall, 180mm long
- 2x Square steel pipe 30mm side, 90mm long
- 4x Square steel pipe 25mm side (should fit into the above one), 400m long
- 4x Washers 24mm outer diameter, 8mm inner diameter
- 3x Screws M8 70mm round cap
- 9x Nyloc M8 nuts
- 3x Flanged nuts M8	
- 8x Screws M8 40mm

## Tools
- welder
- 3d printer
- tap&die M8
- drill

## Printed parts
- base bottom !(model)[basebottom.stl]
- base top !(model)[basetop.stl]
- base cup !(model)[basecup.stl]
- nut cover !(model)[nutcover.stl]
- leg cover !(model)[legcover.stl]
- rod centering blocks !(model)[rod.stl]
- nut holding block !(model)[nutblock.stl]
